services:
  mysql_spa:
    image: mysql:8.0
    container_name: mysql_spa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spa_db
      MYSQL_USER: spa_user
      MYSQL_PASSWORD: spa_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spa_network

  backend_spa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_spa
    depends_on:
      - mysql_spa
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_spa:3306/spa_db
      SPRING_DATASOURCE_USERNAME: spa_user
      SPRING_DATASOURCE_PASSWORD: spa_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - spa_network

volumes:
  mysql_data:

networks:
  spa_network:
